***Тема “Вычисления с помощью Numpy”***

**Задание 1.**


In [2]:
import numpy as np

In [6]:
a = np.array ( [[1, 6],
                [2,8],
                [3, 11],
                [3, 10],
                [1, 7]])

print(a)


[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [8]:
mean_a = a.mean(axis=0)

mean_a


array([2. , 8.4])

**Задание 2.**


In [9]:
a_centered = a - mean_a

a_centered


array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

**Задание 3.**

Так и не понял, что требуется о меня в этой задаче...


***Тема “Работа с данными в Pandas”***

**Задание 1.**


In [10]:
import pandas as pd


In [11]:
authors = pd.DataFrame(
    {
        'author_id': [1, 2, 3],
        'author_name': ['Тургенев', 'Чехов', 'Островский']
    }
)

authors


author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [12]:
book = pd.DataFrame(
    {
        'author_id': [1, 1, 1, 2, 2, 3, 3],
        'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
        'price': [450, 300, 350, 500, 450, 370, 290]
    }
)

book


author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

**Задание 2.**

In [15]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'outer')

authors_price


author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

**Задание 3.**

In [16]:
top5 = authors_price.nlargest(5, 'price')

top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

**Задание 4.**

In [34]:
authors_stat = authors_price.groupby('author_name')

a_min = authors_stat.agg({'price': 'min'})

a_max = authors_stat.agg({'price': 'max'})

a_mean = authors_stat.agg({'price': 'mean'})

a_min_max = pd.merge(a_min, a_max, on = 'author_name', how = 'outer')

authors_stat = pd.merge(a_min_max, a_mean, on = 'author_name', how = 'outer')

authors_stat = authors_stat.rename(columns={'price_x': 'min_price', 'price_y': 'max_price', 'price': 'mean_price'}) 

authors_stat



min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000